version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - /root/.m2  # Cache Maven dependencies
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://13.39.246.141:6543/postgres?ssl=true&sslmode=require&prepareThreshold=0
      - SPRING_DATASOURCE_USERNAME=postgres.gcftmbhqlkqcamiwjoky
      - SPRING_DATASOURCE_PASSWORD=Oujda@oujda
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules  # Prevent overwriting node_modules
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
